[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
flutter_rust_bridge = "1.38.1"
lazy_static = "1.4.0"
once_cell = "1.13.0"

[lib]
crate-type = ["cdylib"]
